### ISSUE TITLE
Metadata - missing full command used

### ISSUE THREAD

**Issue by kellynm** [ncsu-landscape-dynamics/r.pops.spread#1]
The data description part of the metadata only includes the module name, not the full command and parameters used.
![capture](https://user-images.githubusercontent.com/32572763/45304195-8f54a600-b4e5-11e8-8093-2a225c5411fa.PNG)

**Comment by wenzeslaus** [comment]
Fixed in b9cf351. Now in GRASS GIS Add-ons as well:
https://trac.osgeo.org/grass/changeset/73311/grass-addons/grass7/raster/r.spread.sod
