### ISSUE TITLE
Naming: r.spread.pest versus r.spread.pops versus something else

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/r.pops.spread#5]
For 1.0.0, we are renaming from _r.spread.sod_ to something more general.

GRASS GIS modules, especially those in the core, usually have descriptive names. Developers use acronyms usually only in clear cases (for the given field), for example _i.vi_ (imagery: vegetation index). It was suggested that in this spirit we could name the module _r.spread.pest_. It is clear what we are spreading and it is short. Longer name pathogen or disease in besides or instead of pest would be always longer, likely too long. There should be only up to one additional dot in the name of GRASS GIS module (in addition to the first one after the main module group/family character or characters, _r_ in our case). It was argued that pest is often used to refer to both pest and pathogen.

However, an early user feedback indicates that _r.spread.pest_ leaves the impression that pathogens are not modeled and the focus is on insect only. Also, it was was argued that not mentioning disease or pathogen explicitly leaves out an important keyword whether in context of searches or peoples' impressions.

Here are two quotes from IPPC document suggesting that IPPC is using pest to mean pathogen as well:

IPPC Regulation of wood packaging material in international trade

http://www.fao.org/3/a-mb160e.pdf

> The International Plant Protection Convention (IPPC) is an international plant health agreement that aims to protect cultivated and wild plants by preventing the introduction and spread of pests. International travel and trade are greater than ever before. As people and commodities move around the world, organisms that present risks to plants travel with them.

> ...deep burial in sites approved by appropriate authorities (NB: the depth of burial may depend on climatic  conditions  and  the  pest  intercepted,  but  is  recommended  to  be  at  least  2 metres. The material should be covered immediately after burial and should remain buried. Note, also, that deep  burial  is  not  a  suitable  disposal  option  for  wood  infested  with  termites  or  some  root  pathogens.)

Here are quotes from a USDA document which at some places uses pest for pathogens, for example "pests (insects, mollusks, pathogens)," but sometimes makes the distinction, for example "other exotic pests and pathogens". Sometimes use adjective to specify which pests as in "rice pathogens and insect pests".

USDA Cut Flowers and Greenery Import Manual

https://www.aphis.usda.gov/import_export/plants/manuals/ports/downloads/cut_flower_imports.pdf

> ...you find pests (insects, mollusks, pathogens), HOLD the shipment and SEND the interception to the nearest PPQ Plant Inspection Station through the proper channels for identification. If you find contaminants (inadmissible plant parts, plant debris, soil)...

> Conifers are regulated to prevent the entry of a wide variety of insect pests (from defoliators to borers) and various pathogens (e.g., cankers and rusts).

> Orysa sativa is regulated from all countries to prevent the entry of rice pathogens and insect pests.

> ...iburnum spp. are regulated to prevent fruit flies (if berries are present) and other exotic pests and pathogens from entering, including light brown apple moth (LBAM) (Epiphyas postvittana).

> USDA–APHIS–PPQ–Imports, Regulations, and Manuals (IRM) issues written permits for commercial mportations of admissible plant material and for the movement of live plants pests, pathogens, and Federal noxious weeds (FNW). 

The same document has a glossary, unfortunately without the word pest.

> **Pathogen**: Organism capable of causing disease in a particular host or range of hosts, and obtaining its nutrients wholly or in part from another living organism, e.g., a microorganism such as a bacterium or fungus.
> **Disease**: Interaction between a pathogen and the plant resulting in damage to the plant. The damage caused is referred to as a symptom.
> **Pest-risk level guide**: aid to determine the extent of  inspection of cut flowers based on pest risk; a risk level is given to kinds of flowers from specific countries.

A possible solution is to use the name of the library (and model), PoPS, i.e. _r.spread.pops_. Using only the name of the model, i.e. _r.pops_, like in case of FUTURES (_r.futures.pga_, _r.futures.demand_, ..., _r.futures_ for the suite) would drop the spread part which is at least saying it is a kind of spread. Naming it _r.pops.spread_ would mean, looking at the FUTURES case or r.stream suite case, that there there is more than one module besides the one for spread. This is not the case now, but it may happen as, similarly to FUTURES, calibration and validation tools are needed.

Obviously the disadvantage of using _r.spread.pops_ (or _r.pops_ or r.pops.spread_) over _r.spread.pest_ is that there is no keyword for pest nor pathogen (which was the criticism of _r.spread.pest_) . Everything is left on the description being provided with the module name which is actually a likely case (searching for non-core GRASS GIS modules with only the names seems unlikely).

**Comment by wenzeslaus** [comment]
The name should be *r.pops.spread*.

* This will allow for other modules such as *r.pops.calibrate*.
* The PoPS name is what we actually want to emphasize since it is a name of the model (rather than trying to claim the generic name in GRASS GIS for PoPS model).
* This follows *r.futures* group (set/suite) of modules from our lab (ncsu-landscape-dynamics).
* The complexity of pest-pathogen-vector is left for the more flexible keywords and description.

**Comment by petrasovaa** [comment]
Renamed
